name = "yt-event-notifier-backend"
main = "backend/main.py"
compatibility_date = "2026-06-04"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "yt_event_notifier_db"
database_name = "yt-event-notifier-db"
database_id = "3e436fbb-c046-4933-93ef-3d7cc0674d06"

[vars]
# Add your environment variables here or in Cloudflare Dashboard
# TELEGRAM_BOT_TOKEN = "..."
# GOOGLE_CLIENT_ID = "..."
# GOOGLE_CLIENT_SECRET = "..."

[triggers]
crons = ["*/15 * * * *"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
